version: '3'
services:
    dnsmasq:
        build: .
        image: xyzrlee/dnscrypt-proxy
        restart: unless-stopped
        ports:
            - "5353:53/tcp"
            - "5353:53/udp"
        cap_add:
            - NET_ADMIN
        volumes:
            - .:/conf:ro
        command: -config /conf/dnscrypt-proxy.toml
