on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: dnscrypt-proxy
  TAG_LATEST: latest
  TAG_CURRENT: ${{ vars.DNSCRYPT_VERSION }}
  VERSION: ${{ vars.DNSCRYPT_VERSION }}

jobs:
  build:
    name: Deploy to ghcr.io
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Build
      run: | 
        ./build.sh
    - name: Build
      run: | 
        docker build \
        --tag ghcr.io/$GITHUB_ACTOR/${{env.IMAGE_NAME}}:${{env.TAG_CURRENT}} \
        --tag ghcr.io/$GITHUB_ACTOR/${{env.IMAGE_NAME}}:${{env.TAG_LATEST}} \
        .
    - name: Docker login
      if: ${{ github.ref_name == 'master' }}
      run: >-
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin ghcr.io
    - name: Push image to GitHub
      if: ${{ github.ref_name == 'master' }}
      run: |
        docker tag dnscrypt-proxy ghcr.io/${{github.repository_owner}}/${{env.IMAGE_NAME}}:${{env.TAG_LATEST}}
        docker push ghcr.io/${{github.repository_owner}}/${{env.IMAGE_NAME}}:${{env.TAG_LATEST}}
        docker tag dnscrypt-proxy ghcr.io/${{github.repository_owner}}/${{env.IMAGE_NAME}}:${{env.TAG_CURRENT}}
        docker push ghcr.io/${{github.repository_owner}}/${{env.IMAGE_NAME}}:${{env.TAG_CURRENT}}
